In [1]:
import tensorflow as tf

In [2]:
%load_ext autoreload
%autoreload 2

import sys
 
# setting path
sys.path.append('../read_data/')
sys.path.append('../')

In [3]:
import numpy as np

In [4]:
y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
# Using 'auto'/'sum_over_batch_size' reduction type.
cce = tf.keras.losses.CategoricalCrossentropy(reduction=tf.losses.Reduction.NONE)
cce(y_true, y_pred).numpy()

2022-09-08 14:59:24.742272: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-08 14:59:24.753852: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-08 14:59:24.754810: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-09-08 14:59:24.756327: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

array([0.05129331, 2.3025851 ], dtype=float32)

In [5]:
np.log(0.95), np.log(0.1)

(-0.05129329438755058, -2.3025850929940455)

In [6]:
from classification_loss import SSDLoss

In [52]:
y_true = tf.constant([[
    [1, 0, 0], 
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    
]], tf.float32)

np.random.seed(42)

y_pred = tf.constant(np.random.uniform(size=(1,32,3)) * 5, tf.float32)

y_pred.shape

TensorShape([1, 32, 3])

In [53]:
layer = tf.keras.layers.Softmax()
y_pred = layer(y_pred)

In [54]:
y_pred[:, 14, :]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.0119784 , 0.9512376 , 0.03678397]], dtype=float32)>

In [55]:
np.log(0.0119784) / 4

-1.1061625627851912

In [59]:
cce(y_true, y_pred).numpy() / 1e-6

array([[3210961.   ,  197774.31 , 4289906.   , 1555046.5  ,   80363.164,
        2121164.2  , 1374545.9  , 1833279.6  , 1865821.8  ,  945749.8  ,
         164530.03 ,  948840.3  , 2082998.8  ,  924457.44 , 4424650.   ,
         508983.5  , 2245819.   , 1628062.9  , 1813317.6  , 1217842.1  ,
        2359336.2  , 1439423.9  , 3367410.   ,  308469.8  , 4518711.   ,
         821156.2  , 2622172.5  ,  256703.14 , 2320794.2  , 1593677.9  ,
        3809700.5  , 1518822.1  ]], dtype=float32)

In [60]:
loss = SSDLoss(negative_mining_ratio = 1)

In [61]:
loss.confidence_loss(y_true, y_pred)

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[      0.,       0.,       0.,       0.,       0.,       0.,
              0.,       0.,       0.,       0.,       0.,       0.,
              0.,       0.,       0.,       0.,       0.,       0.,
              0.,       0.,       0.,       0.,       0.,       0.,
        4518711.,       0.,       0.,       0.,       0.,       0.,
              0.,       0.]], dtype=float32)>